- name: install go lang
  ansible.builtin.package:
    name: golang
    state: present

- name: install dependencies
  ansible.builtin.shell: "{{item}}"
  loop:
  - go mod init dispatch
  - go get
  - go build
  args:
    chdir: /app