  - name: install mysql
    ansible.builtin.package:
      name: mysql
      state: present

  - name: check cities schema exists or not
    ansible.builtin.command:  mysql -h {{mysql_host}} -uroot -p{{mysql_password}} -sN -e "SELECT COUNT(*) FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'cities'"
    register: schema

  - name: print output
    ansible.builtin.debug:
      msg: "schema output: {{schema}}"

  - name: Load Schema
    ansible.builtin.shell: mysql -h mysql.awstraining.tech -uroot -p{{mysql_password}} < /app/schema/shipping.sql 
    when: schema.stdout != "1"